_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 2  # AD, NA
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
DATASETS:
  TRAIN : ("CVC-VideoClinicDB_train",)
  TEST : ("CVC-VideoClinicDB_test",)
DATALOADER:
  NUM_WORKERS : 2
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 26775
  STEPS: (0, 13393, 21420)
OUTPUT_DIR: "./work_dirs/exp56/"