_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/cascade_mask_rcnn_R_50_FPN_1x.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 2  # AD, NA
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
DATASETS:
  TRAIN : ("CVC-VideoClinicDB_train",)
  TEST : ("CVC-VideoClinicDB_test",)
DATALOADER:
  NUM_WORKERS : 2
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  MAX_ITER: 100000
OUTPUT_DIR: "./work_dirs/exp51/"