_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/faster_rcnn_R_50_FPN_3x.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128   # faster, and good enough for this toy dataset (default: 512)
    NUM_CLASSES: 2  # AD, NA
DATASETS:
  TRAIN : ("CVC-VideoClinicDB_train",)
  TEST : ("CVC-VideoClinicDB_test",)
DATALOADER:
  NUM_WORKERS : 2
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  MAX_ITER: 50000
OUTPUT_DIR: "./work_dirs/exp50/"