_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1  # AD, NA
DATASETS:
  TRAIN : ("CVC-VideoClinicDB_train_val_polyp", "cvc-612", "cvc-300", "HDClassif",)
  TEST : ("CVC-VideoClinicDB_test",)
DATALOADER:
  NUM_WORKERS : 2
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 26775
OUTPUT_DIR: "./work_dirs/exp68/"