_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 1  # AD, NA
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
DATASETS:
  TRAIN : ("cvc-612", "cvc-300",)
  TEST : ("CVC-VideoClinicDB_test_polyp",)
DATALOADER:
  NUM_WORKERS : 2
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 4730
OUTPUT_DIR: "./work_dirs/exp61/"