_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: CascadeROIHeads
    NUM_CLASSES: 1  # AD, NA
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
DATASETS:
  TRAIN : ("CVC-VideoClinicDB_train_val_polyp", "cvc-612", "cvc-300", "HDClassif",)
  TEST : ("CVC-VideoClinicDB_test_polyp",)
INPUT:
  FLIPS: False
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 26775
OUTPUT_DIR: "./work_dirs/exp76/"